### PR TITLE
Use minutes and seconds for build patch versions

### PR DESCRIPTION
**Pull request by mayerwin**

### CODE REVIEW

**Comment by mayerwin** [comment]
How is it possible to have NuGet.Packer use the build number generated by Visual Studio? For example if we have:

```
assembly: AssemblyVersion("1.0.*")]
//[assembly: AssemblyFileVersion("1.0.0.0")]
```

which will already auto increment the build number.

**Comment by jchadwick** [comment]
Thank you for the PR!

I was deliberately trying to keep the length short so it is readable. I'm ok with adding minutes, but the reason to add seconds is if there is the possibility that there will be 2 builds in the same minute. Is that a problem you were having or expect to have?  IOW is it worth the longer version number?

Also, interested in hearing more about the scenario in which you'd want to use VS's version number. In my experience that has not been deterministic enough to be useful. 

My thinking behind this implementation is that you either want a dynamic, unique and incremental version number created for you OR managed externally (i.e. by the CI server) and passed in as a build parameter.

**Comment by mayerwin** [comment]
I agree seconds precision may be overkill, however what surprised me was that the version number was not increasing as I was fixing a few bugs, which prevented me from re-uploading it to a private NuGet repository. And I had to go in the source code of NuGet.Packer to understand it was using the hour as the smallest unit to generate a new build number.

The objective would be to apply the principle of least surprise. The standard usage with `nuget pack *.csproj` is to use the assembly's version number as the NuGet package version number. People trying to switch to NuGet.Packer may be surprised of this change in behavior. But it is still a good option to have to generate an incremental build number for those who would want it and not change the real build version number.
So what could make all this work and get closer to what VS is already able to do would be to:
- Use the assembly's build number by default, and improve the documentation to mention the possibility to make incremental build numbers automatically by simply changing the assembly version to take advantage of the `*` token.
- Include an option to automatically generate a time-based NuGet-specific build number (at least with minute precision, with clear documentation), though IMHO it would be better to also reflect this in the real build number, so this option may be deprecated in favor of the built-in way of achieving the same. 
- Continue offering the possibility to pass a version number passed externally (I am personally not in this configuration).

I personally do not care much about the version length if it is generated automatically; those who want to keep it really short could just manually set the assembly version number to something other than `*`.

**Comment by jchadwick** [comment]
If you're fine with the longer version number, I guess I am, too. :)

I think we're fine with this PR, and I think the discussion about supporting the AssemblyVersion attribute is legitimate.  I've opened up issue #11 to track it.

**Comment by mayerwin** [comment]
Ouch, this seems to have broken NuGet.Packer: upon compilation VS reports: `1.0.16112304202014 is not a valid version string`.

`"NuGet.exe" pack "myproject.csproj" -Properties "Configuration=Release;Platform=x86;TargetPath=bin\Release\CR.Common.Core.dll" -NonInteractive -OutputDirectory "bin\Release" -symbols -Version 1.0.161123042014`

It seems there is a max length at play as removing 2 characters work. Until the other suggestions have been implemented (I am interested in helping out but too busy right now), I am going to submit another PR.

**Pull request merged**
